#!/bin/sh
# Builds the example as a release app of its own, in e2e mode (EXPO_PUBLIC_E2E=1, bundled in: no Metro, no Expo
# Go), and installs it on the simulator or emulator, for E2E_APP=build npm run e2e:ios|android.
#   e2e-build.sh ios|android       NO_INSTALL=1 builds without installing (CI builds once, then installs per job)
# The native projects (ios/, android/) are generated by expo prebuild and aren't kept in git.
# MAESTRO_DEVICE picks the simulator or emulator, as for e2e.sh. ANDROID_ARCH is the one CPU architecture the
# Android app is built for, the emulator's: arm64-v8a (the default, Apple silicon) or x86_64 (CI's Linux runners).
set -e
platform="$1"
export EXPO_PUBLIC_E2E=1
# CocoaPods needs a UTF-8 locale
export LANG="${LANG:-en_US.UTF-8}"
export ANDROID_HOME="${ANDROID_HOME:-$HOME/Library/Android/sdk}"

case "$platform" in
  ios)
    CI=1 npx expo prebuild --platform ios
    xcodebuild -workspace ios/ListScrubber.xcworkspace -scheme ListScrubber -configuration Release \
      -sdk iphonesimulator -destination 'generic/platform=iOS Simulator' -derivedDataPath ios/build \
      CODE_SIGNING_ALLOWED=NO -quiet build
    app=ios/build/Build/Products/Release-iphonesimulator/ListScrubber.app
    echo "Built $app"
    [ -n "$NO_INSTALL" ] || xcrun simctl install "${MAESTRO_DEVICE:-booted}" "$app"
    ;;
  android)
    CI=1 npx expo prebuild --platform android
    (cd android && ./gradlew assembleRelease --build-cache --console=plain -q -PreactNativeArchitectures="${ANDROID_ARCH:-arm64-v8a}")
    apk=android/app/build/outputs/apk/release/app-release.apk
    echo "Built $apk"
    [ -n "$NO_INSTALL" ] || adb ${MAESTRO_DEVICE:+-s "$MAESTRO_DEVICE"} install -r "$apk"
    ;;
  *)
    echo "usage: e2e-build.sh ios|android" >&2
    exit 1
    ;;
esac
